export const FETCH_AIRLINE_REQUEST = 'FETCH_AIRLINE_REQUEST';
export const FETCH_AIRLINE_SUCCESS = 'FETCH_AIRLINE_SUCCESS';
export const FETCH_AIRLINE_FAILURE = 'FETCH_AIRLINE_FAILURE';
export const ADD_AIRLINE = 'ADD_AIRLINE';